### ISSUE TITLE
UDP Multicast

### ISSUE THREAD

**Issue by afrocubanito** [OlivierLeBozec/viewts#21]
Bonjour Olivier,

En cherchant un outil pour mesurer la stabilité d'un stream ts, je suis tombé sur ton projet.
Je voulais savoir si il était possible de lire un flux udp ou rtp, multicast ou unicast ?

Bien à toi,
Cordaliss

**Comment by OlivierLeBozec** [comment]
Salut Cordaliss,
Il faut d'abord faire une capture du flux IP. Ensuite tu peux le passer dans l'outil.
Je n'ai pas d'idée sur un outil (public) pour la capture a part peut-être wireshark.
Sinon je crois que VLC lit du udp/rtp unicast et multicast.

De mémoire le rtp contient des timestamps pas le udp.
Olivier.

**Comment by OlivierLeBozec** [comment]
Je pense que ffmpeg peut transformer un fichier IP en ts.
https://stackoverflow.com/questions/26454833/recording-ip-camera-stream-with-ffmpeg
